version: '3'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ${VOLUME_PATH}/mysql57/storage:/var/lib/mysql
      - ${VOLUME_PATH}/mysql57/config:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
  postgresql:
    image: postgres:12
    volumes:
      - ${VOLUME_PATH}/postgresql/data:/var/lib/postgresql/data 
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
  mongodb:
    image: mongo
    volumes:
      - ${VOLUME_PATH}/mongodb/mongo:/etc/mongo
      - ${VOLUME_PATH}/mongodb/mongo:/data/db
  redis:
    image: redis
  jupyter:
    build:
      context: .
      args:
        - password=${JUPYTER_PASSWORD}
    volumes:
      - ${VOLUME_PATH}/notebook/:/notebook/
    ports:
      - "${JUPYTER_PORT}:8888"
